### ISSUE TITLE
Consider / discuss running test on pushing in any branch. 

### ISSUE THREAD

**Issue by kowodo** [petrmvala/foodshopper#10]
it seems to me that the default configuration in maven.yml 
does run only on creating PR to [main]
I would like to discuss the pros and cons of that approach.

**Comment by petrmvala** [comment]
Correct. Now we're using only the `main` branch, no `develop` or any other standing branch. Therefore, all pull requests going into `main` are being built. Do you feel that it would be useful to build on pull requests going to other branches too?
IMO it would be overkill.

**Comment by kowodo** [comment]
Agree.
